# Generated by Django 5.0 on 2023-12-22 00:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('supplier_code', models.CharField(max_length=150)),
                ('supplier_name', models.CharField(max_length=150)),
                ('messure_unit', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(200000), django.core.validators.MinValueValidator(1)])),
                ('purchase_price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(1)])),
                ('sales_price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(1)])),
                ('percent', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('purchase_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 1, 1)), django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 12, 21))])),
            ],
        ),
    ]
